spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 744618026
    url: jdbc:mysql://49.234.70.188/travel?characterEncoding=utf-8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5MB

  resources:
    static-locations:
      - classpath:/resources/
      - classpath:/static/
      - classpath:/templates/
  redis:
    database: 0
    host: 49.234.70.188
    password: 744618026
    jedis:
      pool:
        max-active: 80
        max-idle: 80
    timeout: 5000
server:
  servlet:
    context-path: /travel