spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 744618026
    url: jdbc:mysql://49.234.70.188/travel?characterEncoding=utf-8&useSSL=false
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5MB
      location: /Users/liuwenjun/IdeaProjects/travel/static
  resources:
    static-locations:
      - classpath:/resources/
      - classpath:/static/
      - classpath:/templates/
  redis:
    database: 0
    host: 192.168.1.105
    jedis:
      pool:
        max-active: 80
        max-idle: 80
    timeout: 10000
    password: 744618026
server:
  servlet:
    context-path: /travel